### ISSUE TITLE
Error in gatsby-docs-kit.yml causes Unhandled Exception

### ISSUE THREAD

**Issue by kkoscielniak** [brainhubeu/gatsby-docs-kit#1]
Erroneous data in `gatsby-docs-kit.yml` causes Unhandled Exception and, ultimately, Gatsby crashes. 

## Steps to reproduce
1. Open `gatsby-docs-kit.yml` 
2. Add duplicate of a key to YAML file: 
```yaml 
items:
- title: Render component when all the permissions match
  file: permissionsMatch.md
items:
- title: Render component when one of the permissions match
  file: oneMatch.md
```
3. Check Gatsby console: 
```sh
error UNHANDLED EXCEPTION

YAMLException: duplicated mapping key at line 29, column -102:
  items:
```
